name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest # Firefox in it
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: DEBUG=eslint:cli-engine npm run lint:all
      - run: npm run build
      - run: npm run test:ut
      - run: cat ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  e2e-test:
    if: ${{ github.repository_owner == 'ringcentral' }}
    runs-on: ubuntu-latest # Firefox in it
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: DEBUG=eslint:cli-engine npm run lint:all
      - run: npm run build
      - run: npm test
        env:
          RC_WP_CALLER_APPKEY: ${{ secrets.RC_WP_CALLER_APPKEY }}
          RC_WP_CALLER_APPSECRET: ${{ secrets.RC_WP_CALLER_APPSECRET }}
          RC_WP_CALLER_SERVER: ${{ secrets.RC_WP_CALLER_SERVER }}
          RC_WP_RECEIVER_APPKEY: ${{ secrets.RC_WP_RECEIVER_APPKEY }}
          RC_WP_RECEIVER_APPSECRET: ${{ secrets.RC_WP_RECEIVER_APPSECRET }}
          RC_WP_RECEIVER_SERVER: ${{ secrets.RC_WP_RECEIVER_SERVER }}
          RC_WP_CALLER_USERNAME: ${{ secrets.RC_WP_CALLER_USERNAME }}
          RC_WP_CALLER_PASSWORD: ${{ secrets.RC_WP_CALLER_PASSWORD }}
          RC_WP_RECEIVER_USERNAME: ${{ secrets.RC_WP_RECEIVER_USERNAME }}
          RC_WP_RECEIVER_PASSWORD: ${{ secrets.RC_WP_RECEIVER_PASSWORD }}
      - run: cat ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
