name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - name: test
        env:
          RC_WP_CLIENT_ID: ${{ secrets.RC_WP_CLIENT_ID }}
          RC_WP_CLIENT_SECRET: ${{ secrets.RC_WP_CLIENT_SECRET }}
          RC_WP_SERVER: ${{ secrets.RC_WP_SERVER }}
          RC_WP_CALLER_JWT_TOKEN: ${{ secrets.RC_WP_CALLER_JWT_TOKEN }}
          RC_WP_RECEIVER_JWT_TOKEN: ${{ secrets.RC_WP_RECEIVER_JWT_TOKEN }}
        run: |
          yarn playwright install --with-deps
          yarn test
      - name: ⬆ Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          path: screenshots
